/run/initialize
#

# source
/gps/source/intensity 1.
/gps/particle gamma


/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 0. 0. 48. cm
/gps/pos/halfx 45 cm
/gps/pos/halfy 15. cm
/gps/pos/halfz 0.5 cm
/gps/pos/paralp 0.523599
/gps/pos/parthe 0.
#.523599
/gps/pos/parphi 0.
#.523599
#/gps/pos/parphi 0.523599


/gps/ang/type iso
# turn source into beam for testing purposes
#/gps/ang/mintheta 180. degree
#/gps/ang/maxtheta 180. degree

/gps/ene/type User
/gps/hist/type energy

  # Americium 241
  #/gps/hist/point 0.0525 1

  # caesium 137
   /gps/hist/point 0.6617 1.0
  # /gps/hist/point 0.662 1.


  # Cobalt 60
  # /gps/hist/point 1.1732 1.0
  # /gps/hist/point 1.332 .0
  # /gps/hist/point 1.3325 1.0

  # Pu-239
  # /gps/hist/point 0.414 1.0
  #
  # U-235
  # /gps/hist/point 0.186 1.0

  # U-235
  # /gps/hist/point 0.186 1.0

  # Tl-208
  # /gps/hist/point 2.614 1.0



/run/printProgress 1000000
/run/beamOn 1000000000



# /run/beamOn 100
