/run/initialize

# source
/gps/source/intensity 1.
/gps/particle gamma

/gps/pos/type Point
/gps/pos/centre 0. 0. -30. cm

/gps/ang/type iso

/gps/ene/type User
/gps/hist/type energy

  # Americium 241
  #/gps/hist/point 0.0525 1

  # caesium 137
  /gps/hist/point 0.6617 1.0
  # /gps/hist/point 0.662 1.

  # Cobalt 60
  #/gps/hist/point 1.1732 1.0
  #/gps/hist/point 1.332 .0
  #/gps/hist/point 1.3325 1.0

  # Pu-239
  # /gps/hist/point 0.414 1.0

  # Pa-234m
  # /gps/hist/point 1.001 1.0

# source 2
/gps/source/add 1.
#/gps/source/intensity 1.
/gps/particle gamma

/gps/pos/type Point
/gps/pos/centre 0. 0. 30. cm

/gps/ang/type iso

/gps/ene/type User
/gps/hist/type energy

  # Americium 241
  #/gps/hist/point 0.0525 1

  # caesium 137
  /gps/hist/point 0.6617 1.0
  # /gps/hist/point 0.662 1.

  # Cobalt 60
  #/gps/hist/point 1.1732 1.0
  #/gps/hist/point 1.332 .0
  #/gps/hist/point 1.3325 1.0

  # Pu-239
  # /gps/hist/point 0.414 1.0

  # Pa-234m
  # /gps/hist/point 1.001 1.0

/run/printProgress 1000000
/run/beamOn 1000000000



# /run/beamOn 100000
